"""empty message

Revision ID: 0a87a10843d9
Revises: a146d5e1de91
Create Date: 2021-10-15 11:06:16.610928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy.types import Text
# revision identifiers, used by Alembic.
revision = '0a87a10843d9'
down_revision = 'a146d5e1de91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp2',
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('dataset', sa.INTEGER(), nullable=True),
    sa.Column('xcol', sqlite.JSON(), nullable=False),
    sa.Column('ycol', sa.CHAR(), nullable=False),
    sa.Column('trainsize', sa.DECIMAL(), nullable=False),
    sa.Column('testsize', sa.DECIMAL(), nullable=False),
    sa.Column('trainsize2', sa.DECIMAL(), nullable=False),
    sa.Column('validsize', sa.DECIMAL(), nullable=False),
    sa.Column('trainamount', sa.INTEGER(), nullable=False),
    sa.Column('testamount', sa.INTEGER(), nullable=False),
    sa.Column('validamount', sa.INTEGER(), nullable=False),
    sa.Column('scaler', sa.CHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset'], ['data.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###
