"""empty message

Revision ID: 7286146227df
Revises: 92177d11a0ee
Create Date: 2021-10-15 11:00:18.651180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7286146227df'
down_revision = '92177d11a0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp2',
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.INTEGER(), nullable=True),
    sa.Column('xcol', sqlite.JSON(), nullable=False),
    sa.Column('ycol', sa.CHAR(), nullable=False),
    sa.Column('trainsize', sa.DECIMAL(), nullable=False),
    sa.Column('testsize', sa.DECIMAL(), nullable=False),
    sa.Column('trainsize2', sa.DECIMAL(), nullable=False),
    sa.Column('validsize', sa.DECIMAL(), nullable=False),
    sa.Column('trainamount', sa.INTEGER(), nullable=False),
    sa.Column('testamount', sa.INTEGER(), nullable=False),
    sa.Column('validamount', sa.INTEGER(), nullable=False),
    sa.Column('scaler', sa.CHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('dataset', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['data.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###
