"""empty message

Revision ID: a146d5e1de91
Revises: 7493263ee44a
Create Date: 2021-10-15 11:05:20.352622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a146d5e1de91'
down_revision = '7493263ee44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp2', 'trainamount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('temp2', 'testamount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('temp2', 'validamount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp2', 'validamount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('temp2', 'testamount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('temp2', 'trainamount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
